language: node_js
node_js:
  - "11"

branches:
  only:
    - dev
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn test

deploy:


notifications:
  email: false